#!/usr/bin/env python3
"""Compare the R and Python tricycle outputs, and score them against a tolerance.

The tolerance is fixed in this file, before any measurement, and is justified in
``TOLERANCE_RATIONALE``. The comparison exits non-zero when it is not met.

``tricyclePosition`` is an angle. It is compared circularly. A naive
``abs(a - b)`` reports about ``2*pi`` for two values that are a hair apart across
the wrap point, which would hide a real agreement and could fake a real one.

Usage:
    python compare.py <r_outdir> <py_outdir> <report.md> [--label NAME]
"""

from __future__ import annotations

import argparse
import sys
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

TWO_PI = 2.0 * np.pi

# ---------------------------------------------------------------------------
# Tolerance, fixed before measuring.
# ---------------------------------------------------------------------------

#: Median circular difference between the two angle vectors, in radians.
TOL_MEDIAN_RAD = 1e-9

#: Largest circular difference over all cells, in radians.
TOL_MAX_RAD = 1e-6

#: Largest positional error in embedding coordinates, in the same units as the
#: projection. An angle is ill conditioned near the origin: a cell whose
#: projected radius is r turns a positional error of e into an angular error of
#: about e / r. This bound is the one that stays meaningful there.
TOL_MAX_ARC = 1e-9

#: Gene means must agree before any angle comparison is scored.
TOL_GENE_MEAN = 1e-12

TOLERANCE_RATIONALE = f"""\
Both implementations do the same three steps in IEEE 754 double precision:
subtract a per-gene mean, take a dot product over a few hundred genes, then
`atan2`. Each step carries a relative error of order 1e-16, and summing a few
hundred terms in a different order costs at most a few more units in the last
place. An agreement of order 1e-13 is therefore what a correct port should
give, and anything at 1e-6 or above indicates a real difference in the
computation, not rounding.

Three bounds are scored, all fixed before measuring:

| Bound | Value | Why this value |
|---|---|---|
| median circular difference | {TOL_MEDIAN_RAD:g} rad | Four orders of magnitude above the expected 1e-13, so ordinary rounding passes, and four orders below the 1e-6 scale at which a real difference shows. |
| maximum circular difference | {TOL_MAX_RAD:g} rad | Per-cell worst case, not a summary. A subpopulation that inverted would blow past it. |
| maximum arc error | {TOL_MAX_ARC:g} | Circular difference times projected radius. `atan2` is ill conditioned near the origin, so a cell sitting almost exactly at the embedding centre can show a large angular difference from a floating-point-sized positional difference. This bound measures the positional difference itself and stays meaningful there. |

The gene means are checked first, at {TOL_GENE_MEAN:g}. If the two sides did not
centre the same numbers, the angle comparison answers a different question.
"""


# ---------------------------------------------------------------------------


def circular_difference(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Shortest angular distance between two angle vectors, in ``[0, pi]``."""
    d = np.abs(np.mod(a - b + np.pi, TWO_PI) - np.pi)
    return d


def _read(path: str) -> pd.DataFrame:
    return pd.read_csv(path, sep="\t", dtype=str)


def _floats(frame: pd.DataFrame, column: str) -> np.ndarray:
    return frame[column].astype(np.float64).to_numpy()


def _quantile_table(name: str, values: np.ndarray) -> List[str]:
    q = np.quantile(values, [0.5, 0.9, 0.99, 1.0])
    return [f"| {name} | {values.mean():.3e} | {q[0]:.3e} | {q[1]:.3e} | "
            f"{q[2]:.3e} | {q[3]:.3e} |"]


def compare(r_dir: str, py_dir: str, report_path: str, label: str,
            anonymise: bool = False) -> int:
    lines: List[str] = []
    failures: List[str] = []

    def check(name: str, value: float, bound: float) -> str:
        ok = value <= bound
        if not ok:
            failures.append(f"{name}: {value:.3e} exceeds {bound:.3e}")
        return "pass" if ok else "**FAIL**"

    r_pos = _read(f"{r_dir}/r_position.tsv")
    py_pos = _read(f"{py_dir}/py_position.tsv")
    r_genes = _read(f"{r_dir}/r_projection_genes.tsv")
    py_genes = _read(f"{py_dir}/py_projection_genes.tsv")
    r_means = _read(f"{r_dir}/r_gene_means.tsv")
    py_means = _read(f"{py_dir}/py_gene_means.tsv")
    r_summary = dict(line.split("\t", 1) for line in
                     open(f"{r_dir}/r_summary.tsv", encoding="utf-8").read().splitlines())
    py_summary = dict(line.split("\t", 1) for line in
                      open(f"{py_dir}/py_summary.tsv", encoding="utf-8").read().splitlines())

    lines.append(f"# Equivalence results: {label}")
    lines.append("")
    lines.append("Generated by `equivalence/compare.py`. Every number below is "
                 "measured, none is quoted from elsewhere.")
    lines.append("")

    # --- Step 1: are the two sides looking at the same thing at all? ---------
    lines.append("## 1. Input identity")
    lines.append("")
    lines.append("The comparison is void unless both sides ran on the same cells, "
                 "the same genes and the same numbers. These checks come first.")
    lines.append("")
    def same_sequence(left: np.ndarray, right: np.ndarray) -> bool:
        return left.shape == right.shape and bool((left == right).all())

    same_cells = same_sequence(r_pos["barcode"].to_numpy(),
                               py_pos["barcode"].to_numpy())
    if not same_cells:
        failures.append("cell barcodes differ in content, order or count")
    same_genes = same_sequence(r_genes["gene"].to_numpy(),
                               py_genes["gene"].to_numpy())
    if not same_genes:
        failures.append(
            f"projection gene sets differ: R {len(r_genes)} genes, "
            f"Python {len(py_genes)} genes, "
            f"{len(set(r_genes['gene']) ^ set(py_genes['gene']))} not shared")
    mean_delta = float(np.abs(_floats(r_means, "mean")
                              - _floats(py_means, "mean")).max()) if same_genes else np.inf
    rot_delta = float(np.abs(
        np.column_stack([_floats(r_genes, "pc1_rot"), _floats(r_genes, "pc2_rot")])
        - np.column_stack([_floats(py_genes, "pc1_rot"), _floats(py_genes, "pc2_rot")])
    ).max()) if same_genes else np.inf

    lines.append("| Check | R | Python | Verdict |")
    lines.append("|---|---|---|---|")
    lines.append(f"| cells | {len(r_pos)} | {len(py_pos)} | "
                 f"{'identical barcodes, same order' if same_cells else '**FAIL**'} |")
    lines.append(f"| projection genes | {len(r_genes)} | {len(py_genes)} | "
                 f"{'identical names, same order' if same_genes else '**FAIL**'} |")
    lines.append(f"| max abs difference in per-gene mean | - | {mean_delta:.3e} | "
                 f"{check('gene means', mean_delta, TOL_GENE_MEAN)} |")
    lines.append(f"| max abs difference in rotation weight | - | {rot_delta:.3e} | "
                 f"{'pass' if rot_delta == 0 else 'differs'} |")
    lines.append("")

    # --- Step 2: the angle ---------------------------------------------------
    r_theta = _floats(r_pos, "theta")
    py_theta = _floats(py_pos, "theta")
    diff = circular_difference(r_theta, py_theta)
    r_pc = np.column_stack([_floats(r_pos, "pc1"), _floats(r_pos, "pc2")])
    py_pc = np.column_stack([_floats(py_pos, "pc1"), _floats(py_pos, "pc2")])
    radius = np.hypot(r_pc[:, 0], r_pc[:, 1])
    arc = diff * radius
    pc_delta = np.abs(r_pc - py_pc).max(axis=1)

    median_d = float(np.median(diff))
    max_d = float(diff.max())
    max_arc = float(arc.max())

    lines.append("## 2. Cell cycle position")
    lines.append("")
    lines.append("`tricyclePosition` is an angle on `[0, 2*pi)`. It is compared "
                 "circularly: the difference is wrapped onto `[0, pi]`, so two "
                 "values either side of zero are correctly read as close.")
    lines.append("")
    lines.append("| Statistic | Value | Bound | Verdict |")
    lines.append("|---|---|---|---|")
    lines.append(f"| median circular difference (rad) | {median_d:.3e} | "
                 f"{TOL_MEDIAN_RAD:.0e} | {check('median', median_d, TOL_MEDIAN_RAD)} |")
    lines.append(f"| maximum circular difference (rad) | {max_d:.3e} | "
                 f"{TOL_MAX_RAD:.0e} | {check('maximum', max_d, TOL_MAX_RAD)} |")
    lines.append(f"| maximum arc error (rad x radius) | {max_arc:.3e} | "
                 f"{TOL_MAX_ARC:.0e} | {check('arc', max_arc, TOL_MAX_ARC)} |")
    lines.append("")
    lines.append("| Quantity | mean | median | p90 | p99 | max |")
    lines.append("|---|---|---|---|---|---|")
    lines.extend(_quantile_table("circular difference (rad)", diff))
    lines.extend(_quantile_table("embedding coordinate difference", pc_delta))
    lines.extend(_quantile_table("arc error", arc))
    lines.append("")

    worst = int(np.argmax(diff))
    order = np.argsort(-diff)[:10]
    lines.append("### The cells that agree least")
    lines.append("")
    lines.append("A median that looks perfect can hide a subpopulation that "
                 "inverted, so the worst cells are named, not summarised.")
    lines.append("")
    if anonymise:
        lines.append("Cells are named by row index. A barcode can carry a "
                     "dataset identifier, so `--anonymise-barcodes` replaces it.")
        lines.append("")
    label_column = "row" if anonymise else "barcode"
    lines.append(f"| rank | {label_column} | circular difference (rad) | "
                 "projected radius | arc error |")
    lines.append("|---|---|---|---|---|")
    for rank, i in enumerate(order, start=1):
        name = str(i) if anonymise else f"`{r_pos['barcode'].iloc[i]}`"
        lines.append(f"| {rank} | {name} | {diff[i]:.3e} | "
                     f"{radius[i]:.3e} | {arc[i]:.3e} |")
    lines.append("")
    n_small = int((radius < np.quantile(radius, 0.01)).sum())
    corr = float(np.corrcoef(np.log10(radius + 1e-300), np.log10(diff + 1e-300))[0, 1])
    lines.append(f"The worst cell sits at projected radius {radius[worst]:.3e}, "
                 f"against a median radius of {np.median(radius):.3e}. Across all "
                 f"cells the log of the circular difference correlates with the log "
                 f"of the radius at r = {corr:.3f}. A negative correlation is the "
                 f"expected signature of `atan2` conditioning: the closer a cell is "
                 f"to the embedding centre, the more a floating-point-sized "
                 f"positional difference moves its angle. {n_small} cells sit in the "
                 f"smallest one percent of radii.")
    lines.append("")

    # --- Step 3: everything else --------------------------------------------
    lines.append("## 3. Other functions")
    lines.append("")
    rows: List[Tuple[str, str]] = []

    try:
        r_stage = _read(f"{r_dir}/r_stage.tsv").fillna("NA")
        py_stage = _read(f"{py_dir}/py_stage.tsv").fillna("NA")
        same = (r_stage["stage"].to_numpy() == py_stage["stage"].to_numpy())
        n_diff = int((~same).sum())
        rows.append(("estimate_schwabe_stage",
                     f"{int(same.sum())}/{len(same)} cells identical, "
                     f"{n_diff} differ"))
        if n_diff:
            failures.append(f"Schwabe stage differs for {n_diff} cells")
    except FileNotFoundError:
        rows.append(("estimate_schwabe_stage", "not run on one side"))

    r_loess = _read(f"{r_dir}/r_loess.tsv")
    py_loess = _read(f"{py_dir}/py_loess.tsv")
    d_direct = float(np.abs(_floats(r_loess, "fitted_direct")
                            - _floats(py_loess, "fitted")).max())
    d_interp = float(np.abs(_floats(r_loess, "fitted_interpolate")
                            - _floats(py_loess, "fitted")).max())
    rows.append(("fit_periodic_loess vs R surface=\"direct\"",
                 f"max abs difference {d_direct:.3e}"))
    rows.append(("fit_periodic_loess vs R default surface=\"interpolate\"",
                 f"max abs difference {d_interp:.3e}"))
    if d_direct > 1e-8:
        failures.append(f"loess direct surface differs by {d_direct:.3e}")

    r_pred = _read(f"{r_dir}/r_loess_pred.tsv")
    py_pred = _read(f"{py_dir}/py_loess_pred.tsv")
    rows.append(("loess prediction curve vs R surface=\"direct\"",
                 f"max abs difference "
                 f"{np.abs(_floats(r_pred, 'y_direct') - _floats(py_pred, 'y')).max():.3e}"))

    try:
        r_pca = _read(f"{r_dir}/r_pca_rotation.tsv")
        py_pca = _read(f"{py_dir}/py_pca_rotation.tsv")
        same_pca_genes = same_sequence(r_pca["gene"].to_numpy(),
                                       py_pca["gene"].to_numpy())
        if not same_pca_genes:
            shared = len(set(r_pca["gene"]) & set(py_pca["gene"]))
            rows.append(("run_pca_cc_genes gene selection",
                         f"R {len(r_pca)} genes, Python {len(py_pca)}, "
                         f"{shared} shared, **order or content differs**"))
            failures.append("run_pca_cc_genes selected a different gene set")
        else:
            rows.append(("run_pca_cc_genes gene selection",
                         f"{len(r_pca)} genes, identical names and order"))
            worst = 0.0
            for column in ("pc1", "pc2"):
                a, b = _floats(r_pca, column), _floats(py_pca, column)
                # A component and its negation describe the same axis, so the
                # sign is compared for consistency and then divided out.
                sign = 1.0 if np.abs(a - b).max() <= np.abs(a + b).max() else -1.0
                worst = max(worst, float(np.abs(a - sign * b).max()))
            rows.append(("run_pca_cc_genes rotation, after matching sign",
                         f"max abs difference {worst:.3e}"))
            if worst > 1e-6:
                failures.append(f"PCA rotation differs by {worst:.3e}")
        r_var = _floats(_read(f"{r_dir}/r_pca_percentvar.tsv"), "percent_var")
        py_var = _floats(_read(f"{py_dir}/py_pca_percentvar.tsv"), "percent_var")
        n = min(r_var.size, py_var.size)
        rows.append(("run_pca_cc_genes percent variance",
                     f"max abs difference over {n} components "
                     f"{np.abs(r_var[:n] - py_var[:n]).max():.3e}"))
    except FileNotFoundError:
        rows.append(("run_pca_cc_genes", "not run on one side"))

    r_den = _read(f"{r_dir}/r_density.tsv")
    py_den = _read(f"{py_dir}/py_density.tsv")
    d_den = float(np.abs(_floats(r_den, "y") - _floats(py_den, "y")).max())
    rows.append(("circular_density vs circular::density.circular",
                 f"max abs difference {d_den:.3e}"))

    for key in ("loess_rsquared_direct", "diagnose_difference"):
        if key in r_summary and key in py_summary:
            rv, pv = float(r_summary[key]), float(py_summary[key])
            rows.append((key, f"R {rv:.12g}, Python {pv:.12g}, "
                              f"difference {abs(rv - pv):.3e}"))

    lines.append("| Function | Result |")
    lines.append("|---|---|")
    for name, value in rows:
        lines.append(f"| {name} | {value} |")
    lines.append("")

    # --- Verdict -------------------------------------------------------------
    lines.insert(2, "")
    verdict = "PASS" if not failures else "FAIL"
    lines.insert(2, f"**Verdict: {verdict}.** "
                    + ("Every bound below was met."
                       if not failures
                       else "Bounds not met: " + "; ".join(failures)))

    lines.append("## Tolerance, fixed before measuring")
    lines.append("")
    lines.append(TOLERANCE_RATIONALE)
    lines.append("")
    lines.append("## Software")
    lines.append("")
    lines.append("| Side | Version |")
    lines.append("|---|---|")
    for key in ("tricycle_version", "r_version"):
        if key in r_summary:
            lines.append(f"| {key.replace('_', ' ')} | {r_summary[key]} |")
    for key in ("tricyclepy_version", "python_version", "perturbation"):
        if key in py_summary:
            lines.append(f"| {key.replace('_', ' ')} | {py_summary[key]} |")
    lines.append("")

    with open(report_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")

    per_cell = pd.DataFrame({
        "cell": (np.arange(len(r_pos)) if anonymise else r_pos["barcode"]),
        "theta_r": r_theta, "theta_py": py_theta,
        "circular_difference": diff, "projected_radius": radius, "arc_error": arc,
    })
    per_cell_path = report_path.rsplit(".", 1)[0] + "_per_cell.tsv.gz"
    per_cell.to_csv(per_cell_path, sep="\t", index=False, compression="gzip")

    print(f"verdict={verdict}")
    print(f"median_circular_difference={median_d:.6e}")
    print(f"max_circular_difference={max_d:.6e}")
    print(f"max_arc_error={max_arc:.6e}")
    print(f"report={report_path}")
    print(f"per_cell={per_cell_path}")
    for failure in failures:
        print(f"failure: {failure}")
    return 0 if not failures else 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("r_dir")
    parser.add_argument("py_dir")
    parser.add_argument("report")
    parser.add_argument("--label", default="R tricycle versus tricycle-py")
    parser.add_argument("--anonymise-barcodes", action="store_true",
                        help="name cells by row index, so a dataset identifier "
                             "in a barcode does not travel with the report")
    args = parser.parse_args()
    sys.exit(compare(args.r_dir, args.py_dir, args.report, args.label,
                     anonymise=args.anonymise_barcodes))
